/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "sa-east-1",
    "aws_cognito_identity_pool_id": "sa-east-1:1f84f063-4e9c-4503-a6b6-e931065d78b5",
    "aws_cognito_region": "sa-east-1",
    "aws_user_pools_id": "sa-east-1_DXdJg7MPW",
    "aws_user_pools_web_client_id": "2vogmioaqadst6t8hr68ru29db",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://2ycsu2jmzfh7llojazvespsqxu.appsync-api.sa-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "sa-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-dzdw5xlk35dwtk4wigvu4neefq",
    "aws_user_files_s3_bucket": "images103740-dev",
    "aws_user_files_s3_bucket_region": "sa-east-1"
};


export default awsmobile;
